apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: devops-depi
  name: devops-depi-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "deployments"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
